[platformio]
default_envs = esp32s3

[env]
lib_ldf_mode = deep+

[env:native]
platform = native
test_framework = unity
build_flags = -std=c++17

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -std=gnu++17
upload_port = /dev/cu.usbmodem575E0212961
monitor_port = /dev/cu.usbmodem575E0212961
monitor_speed = 115200
