[platformio]
default_envs = esp32s3

[env]
lib_ldf_mode = deep+
extra_scripts =
  pre:scripts/platformio_build_id.py
  pre:scripts/platformio_product_definition.py
  post:scripts/merge_esp32s3_firmware.py

[env:native]
platform = native
test_framework = unity
build_flags = -std=c++17
build_src_filter = -<main.cpp> -<platform/*>

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<*> -<platform/rp2040.cpp>
build_unflags =
  -std=gnu++11
  -DARDUINO_USB_MODE=1
build_flags =
  -std=gnu++17
  -DARDUINO_USB_MODE=0
upload_protocol = esp-builtin

[env:rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#aa70b802be8851668053d4f09734e4089fe41932
board = vccgnd_yd_rp2040
framework = arduino
lib_deps =
  adafruit/Adafruit NeoPixel@1.15.5
  olikraus/U8g2@2.36.18
board_build.core = earlephilhower
board_build.usb_stack = tinyusb
upload_protocol = picotool
build_src_filter = +<*> -<platform/esp32s3.cpp>
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DUSE_TINYUSB
