schema_version: 1
product:
  display_name: WBSEN-K18
  family_id: kivo-workbench
  variant_id: kivo-workbench-rp-k18-disp-encp
  hardware_revision: 2
  product_version_id: kivo-workbench-rp-k18-disp-encp-r02
  capabilities:
  - disp
  - encp
layout:
  id: kivo-workbench-rp-k18-disp-encp
  name: WBSEN-K18
  groups:
  - id: keys
    columns: 6
    buttons:
    - id: KEY_1
      label: K1
    - id: KEY_2
      label: K2
    - id: KEY_3
      label: K3
    - id: KEY_4
      label: K4
    - id: KEY_5
      label: K5
    - id: KEY_6
      label: K6
  - id: group-2
    columns: 6
    buttons:
    - id: KEY_7
      label: K7
    - id: KEY_8
      label: K8
    - id: KEY_9
      label: K9
    - id: KEY_10
      label: K10
    - id: KEY_11
      label: K11
    - id: KEY_12
      label: K12
  - id: group-3
    columns: 6
    buttons:
    - id: KEY_13
      label: K13
    - id: KEY_14
      label: K14
    - id: KEY_15
      label: K15
    - id: KEY_16
      label: K16
    - id: KEY_17
      label: K17
    - id: KEY_18
      label: K18
hardware_profile:
  id: WBSEN-K18
  name: 工作站v1
  board_profile_id: yd-rp2040
  debounce_ms: 30
  sh1106:
    sda: 26
    scl: 27
    control_panel:
      type: ec11_confirm_back
      confirm: 22
      encoder_press: 28
      encoder_a: 21
      encoder_b: 20
      back: 19
  inputs:
  - type: direct
    id: direct-1
    keys:
      KEY_1: 1
      KEY_10: 10
      KEY_11: 11
      KEY_12: 12
      KEY_13: 13
      KEY_14: 14
      KEY_15: 15
      KEY_16: 16
      KEY_17: 17
      KEY_18: 18
      KEY_2: 2
      KEY_3: 3
      KEY_4: 4
      KEY_5: 5
      KEY_6: 6
      KEY_7: 7
      KEY_8: 8
      KEY_9: 9
