"""Bake the vendored Runner Gallery artwork for the OLED.

Run: uv run --with pillow python scripts/generate_runcat_sprites.py
Frames are sorted numerically, share one crop for the whole cycle, and use the
same full-height / right-side metrics layout as the approved candidate preview.
"""

import json
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
WIDTH, HEIGHT = 96, 64


def main():
    assets = ROOT / "assets/runcat"
    manifest = json.loads((assets / "manifest.json").read_text())
    lines = [
        "// Generated by scripts/generate_runcat_sprites.py.",
        "// Adapted from Runner Gallery; Apache-2.0. See assets/runcat/NOTICE.md.",
        "#pragma once", "", '#include "RunCat.h"', "", "namespace {",
    ]
    runners = manifest["runners"]
    for index, runner in enumerate(runners):
        files = sorted((assets / runner["name"]).glob("*.png"),
                       key=lambda path: int(re.search(r"(\d+)\.png$", path.name)[1]))
        assert len(files) == runner["frames"]
        originals = [Image.open(path).convert("RGBA").getchannel("A") for path in files]
        boxes = [frame.getbbox() for frame in originals]
        assert all(boxes), f"Empty frame in {runner['name']}"
        crop = (min(box[0] for box in boxes), min(box[1] for box in boxes),
                max(box[2] for box in boxes), max(box[3] for box in boxes))
        width = min(WIDTH, (crop[2] - crop[0]) * HEIGHT // (crop[3] - crop[1]))
        lines.append(f"constexpr RunCatBitmap kRunner{index}[] = {{ // {runner['name']}")
        for original in originals:
            alpha = original.crop(crop).resize((width, HEIGHT), Image.Resampling.LANCZOS)
            sprite = alpha.point(lambda value: 255 if value >= 128 else 0, mode="1")
            frame = Image.new("1", (WIDTH, HEIGHT))
            frame.paste(sprite, ((WIDTH - width) // 2, 0))
            data = frame.tobytes()
            assert len(data) == WIDTH * HEIGHT // 8
            lines.append("  {{")
            for offset in range(0, len(data), 24):
                lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 24]) + ",")
            lines.append("  }},")
        lines.append("};")
    lines.extend([
        "struct RunCatSprites { const RunCatBitmap *frames; std::uint8_t count; };",
        "constexpr RunCatSprites kRunCatSprites[] = {",
    ])
    for index, runner in enumerate(runners):
        lines.append(f"  {{kRunner{index}, {runner['frames']}}},")
    lines.extend([
        "};",
        "static_assert(sizeof(kRunCatSprites) / sizeof(kRunCatSprites[0]) ==",
        "              static_cast<unsigned>(RunCatAnimation::Count));",
        "}", "",
    ])
    (ROOT / "lib/gpio_trigger/src/RunCatSprites.h").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
