schema_version: 1
product:
  display_name: WBAS-K18
  family_id: kivo-workbench
  variant_id: kivo-workbench-rp-k18-mic-spk-disp-encp
  hardware_revision: 1
  product_version_id: kivo-workbench-rp-k18-mic-spk-disp-encp-r01
  capabilities:
  - mic
  - spk
  - disp
  - encp
layout:
  id: kivo-workbench-rp-k18-mic-spk-disp-encp
  name: WBAS-K18
  groups:
  - id: keys
    columns: 6
    buttons:
    - id: K1
      label: K1
    - id: K2
      label: K2
    - id: K3
      label: K3
    - id: K4
      label: K4
    - id: K5
      label: K5
    - id: K6
      label: K6
  - id: group-2
    columns: 6
    buttons:
    - id: K7
      label: K7
    - id: K8
      label: K8
    - id: K9
      label: K9
    - id: K10
      label: K10
    - id: K11
      label: K11
    - id: K12
      label: K12
  - id: group-3
    columns: 6
    buttons:
    - id: K13
      label: K13
    - id: K14
      label: K14
    - id: K15
      label: K15
    - id: K16
      label: K16
    - id: K17
      label: K17
    - id: K18
      label: K18
hardware_profile:
  id: hardware
  name: Default hardware
  board_profile_id: yd-rp2040
  debounce_ms: 30
  sh1106:
    sda: 28
    scl: 29
    control_panel:
      type: ec11_confirm_back
      confirm: 19
      encoder_press: 20
      encoder_a: 21
      encoder_b: 22
      back: 26
  inputs:
  - type: direct
    id: direct-1
    keys:
      K1: 1
      K10: 10
      K11: 11
      K12: 12
      K13: 13
      K14: 14
      K15: 15
      K16: 16
      K17: 17
      K18: 18
      K2: 2
      K3: 3
      K4: 4
      K5: 5
      K6: 6
      K7: 7
      K8: 8
      K9: 9
